// Optional: NODE_PATH=<installed Playwright directory> node tests/test_web_browser.cjs <launch-url>
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const url = process.argv[2]; assert(url, 'Pass a running peon-code-web launch URL');
  const token = new URL(url).hash.slice(1);
  const browser = await chromium.launch({headless: true, chromiumSandbox: false});
  try {
    const page = await browser.newPage({viewport: {width: 1440, height: 950}});
    await page.route('**/app.js', async route => {
      const response = await route.fetch(), script = await response.text();
      assert(script.includes('const BOX_WAIT_MS = 10000;'));
      await route.fulfill({response, body: script.replace('const BOX_WAIT_MS = 10000;', 'const BOX_WAIT_MS = 1000;')});
    });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error' && /Content Security|Refused|unsafe/i.test(message.text())) errors.push(message.text()); });
    const roles = [
      {id: '%5', name: 'Builder', role: 'worker', session: 'alpha'},
      {id: '%2', name: 'Reviewer', role: 'reviewer', session: 'alpha'},
      {id: '%3', name: 'Boss', role: 'manager', session: 'alpha'},
      {id: '%8', name: 'Lead', role: 'manager', session: 'zeta'},
      {id: '%9', name: 'Check', role: 'reviewer', session: 'zeta'},
      {id: '%10', name: 'Build', role: 'worker', session: 'zeta'}
    ];
    for (const pane of roles) pane.identity = 'first:' + pane.id;
    let empty = false, blocked = true, explainDelay = 0, sendError = null, dismissedSession = null;
    const revision = Object.fromEntries(roles.map(pane => [pane.id, 0]));
    const menu = {};
    const screen = {};
    const styledScreen = {};
    const cursorY = {};
    const menuShown = {};
    const sent = [];
    const buttons = [
      {name: 'Code summary', description: 'Summarize code changes.', prompt: 'Summarize the code changes on this branch: diff against the base branch (main, or master if main is absent) plus uncommitted changes, grouped by file, what changed and why, short.'},
      {name: 'Commit all', description: 'Commit all changes without pushing.', prompt: 'Commit all changes in this repository with a descriptive commit message. Do not push.'},
      {name: 'Push all', description: 'Commit changes and push the current branch.', prompt: 'Push committed work to the remote. If the working tree has uncommitted changes, first commit them all with a descriptive commit message, then push. Push the current branch to its upstream, never force-push.'}
    ];
    let buttonGets = 0, buttonError = null;
    const createdButtons = [];
    await page.route('**/api/buttons', route => {
      assert.equal(route.request().headers()['x-peon-token'], token);
      if (route.request().method() === 'GET') {
        buttonGets++;
        if (buttonError) return route.fulfill({status: 503, json: {error: buttonError}});
        return route.fulfill({json: buttons});
      }
      const data = route.request().postDataJSON();
      createdButtons.push(data);
      if (buttons.some(button => button.name === data.name)) return route.fulfill({status: 409, json: {error: 'Button already exists'}});
      buttons.push(data); buttons.sort((a, b) => a.name.localeCompare(b.name));
      return route.fulfill({json: buttons});
    });
    const firstLine = "It's quoted 日本語 <script>alert('x')</script>.";
    const output = "\x1b[38;2;200;30;40mIt's \x1b[38;5;46;48;2;10;20;30mquoted 日本語 <script>alert('x')</script>.\x1b[0m\n" +
      '\x1b[91mBright\x1b[48;5;17mBlue bg\x1b[38:2::1:2:3mColon RGB\x1b[1;3;4mStyle\x1b[0mAfter\n' + 'A line of agent output.\n'.repeat(70);
    let joinedHistory = false;
    const historyRequests = [];
    const joinedLines = Array.from({length: 60}, (_, i) => 'Logical ' + i + ' ' + 'x'.repeat(3000));
    await page.route('**/api/panes*', route => {
      assert.equal(route.request().headers()['x-peon-token'], token);
      const query = new URL(route.request().url()).searchParams;
      const lines = Number(query.get('lines') || 1000);
      if (joinedHistory) historyRequests.push({pane: query.get('pane'), lines});
      return route.fulfill({json: {panes: empty ? [] : roles.filter(pane => pane.session !== dismissedSession).map(pane => ({...pane, projectDir: '/work/' + pane.session + ' project', command: 'codex', output: joinedHistory && pane.id === '%3' ? joinedLines.slice(-lines / 50).join('\n') : output + revision[pane.id] + (menu[pane.id] || ''), history: joinedHistory && pane.id === '%3' ? 3000 : undefined, screen: screen[pane.id] || '', styledScreen: styledScreen[pane.id] ?? screen[pane.id] ?? '', cursorY: cursorY[pane.id] ?? -1, menu: !!menuShown[pane.id], defaultStyle: 'fg=#abcdef,bg=#123456'}))}});
    });
    await page.route('**/api/dismiss', route => {
      assert.deepEqual(route.request().postDataJSON(), {session: 'zeta'});
      return route.fulfill({json: {message: 'peon-code: killing session zeta'}});
    });
    await page.route('**/api/explain', async route => {
      sent.push(route.request().postDataJSON());
      if (explainDelay) await new Promise(resolve => setTimeout(resolve, explainDelay));
      return route.fulfill({status: blocked ? 409 : 200, json: blocked ? {error: 'target box busy'} : {message: 'Explained'}});
    });
    await page.route('**/api/send', async route => {
      const data = route.request().postDataJSON();
      sent.push(data);
      const error = sendError || (!data.append && blocked ? 'target box busy' : null);
      await new Promise(resolve => setTimeout(resolve, 300));
      await route.fulfill({status: error ? 409 : 200, json: error ? {error} : {message: 'Message sent'}});
    });
    let keyRequest, keyDelay = 0, keyCount = 0;
    await page.route('**/api/keys', async route => {
      keyCount++;
      keyRequest = route.request().postDataJSON();
      if (keyDelay) await new Promise(resolve => setTimeout(resolve, keyDelay));
      await route.fulfill({json: {message: 'Key sent'}});
    });
    const card = id => page.locator(`.pane[data-pane="${id}"]`);
    const promptButton = (id, name) => card(id).locator('.prompt-buttons').getByRole('button', {name, exact: true, includeHidden: true});
    const paneTab = id => page.locator(`#agents [data-key="${id}:${roles.find(pane => pane.id === id).identity}"]`);
    const sessionTab = name => page.locator(`#sessions [data-key="${name}"]`);
    async function selectFirstLine() {
      await card('%3').locator('.output').evaluate(el => {
        el.scrollTop = 0;
        const nodes = el.querySelectorAll('span'); const range = document.createRange();
        range.setStart(nodes[0].firstChild, 0); range.setEnd(nodes[1].firstChild, nodes[1].textContent.length);
        getSelection().removeAllRanges(); getSelection().addRange(range);
      });
      await page.waitForFunction(() => !document.querySelector('.pane:not([hidden]) .explain').disabled);
    }
    async function clearSelection(id) {
      await page.evaluate(() => getSelection().removeAllRanges());
      await page.waitForFunction(id => document.querySelector(`.pane[data-pane="${id}"] .state`).textContent === 'Live', id);
    }
    async function checkTabFocus(id) {
      const before = keyCount;
      await card(id).locator('.output').press('Tab');
      assert(await card(id).locator('.message-form textarea').evaluate(el => document.activeElement === el));
      await card(id).locator('.message-form textarea').press('Shift+Tab');
      assert(await card(id).locator('.output').evaluate(el => document.activeElement === el));
      assert.equal(keyCount, before, 'Focus navigation stays in the browser');
    }
    await page.goto(url); await page.waitForSelector('.pane:not([hidden])');
    await promptButton('%3', 'Code summary').waitFor();
    assert.equal(buttonGets, 1);
    assert.deepEqual(await card('%3').locator('.prompt-buttons button').allTextContents(), ['Code summary', 'Commit all', 'Push all']);
    assert.equal(await promptButton('%3', 'Code summary').getAttribute('title'), buttons[0].description);
    assert.equal(await page.locator('.pane:not([hidden])').getAttribute('data-pane'), '%3');
    assert.deepEqual(await page.locator('#agents button').allTextContents(), ['Boss · manager', 'Reviewer · reviewer', 'Builder · worker']);
    assert.equal(await page.locator('.tab.unread').count(), 0);
    assert.equal(await page.locator('#project-path').textContent(), 'Folder: /work/alpha project');
    assert.equal(await page.locator('#right-click').isChecked(), true);
    const dismissStatus = page.locator('#dismiss-status');
    await sessionTab('zeta').click();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#dismiss').click();
    await page.waitForFunction(() => document.querySelector('#dismiss-status').textContent === 'peon-code: killing session zeta' && !document.querySelector('#dismiss').disabled);
    await sessionTab('zeta').click();
    assert(await dismissStatus.isVisible(), 'Same session keeps dismiss status');
    await sessionTab('alpha').click();
    assert(await dismissStatus.isHidden(), 'Another session hides dismiss status');
    await sessionTab('zeta').click();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#dismiss').click();
    await page.waitForFunction(() => document.querySelector('#dismiss-status').textContent === 'peon-code: killing session zeta' && !document.querySelector('#dismiss').disabled);
    dismissedSession = 'zeta';
    await sessionTab('zeta').waitFor({state: 'detached'});
    assert(await dismissStatus.isHidden(), 'Refresh hides completed dismiss status');
    assert(await card('%3').isVisible());
    dismissedSession = null;
    await sessionTab('zeta').waitFor();
    const selectableOutput = card('%3').locator('.output');
    await checkTabFocus('%3');
    const navigationKeyCount = keyCount;
    await card('%3').locator('.message-form textarea').focus();
    for (const control of [card('%3').locator('.message-form button'), ...buttons.map(button => promptButton('%3', button.name)), card('%3').locator('.add-button'), card('%3').locator('.keys-toggle')]) {
      await page.keyboard.press('Tab');
      assert(await control.evaluate(el => document.activeElement === el), 'Tab reaches every enabled control');
    }
    assert.equal(keyCount, navigationKeyCount, 'Native Tab navigation sends no keys');
    await selectableOutput.evaluate(el => { el.scrollTop = 0; });
    const selectionBox = await selectableOutput.locator('span').first().boundingBox();
    await page.mouse.move(selectionBox.x + 1, selectionBox.y + selectionBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(selectionBox.x + selectionBox.width - 1, selectionBox.y + selectionBox.height / 2, {steps: 5});
    await page.mouse.up();
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Paused');
    assert.equal(await card('%3').locator('.selection-note').textContent(), 'Updates paused while selected');
    assert.equal(await card('%3').locator('.resume').count(), 0);
    revision['%3']++;
    await page.waitForFunction(() => cards.get('%3:first:%3').latest.output.endsWith('1'));
    assert((await selectableOutput.textContent()).endsWith('0'));
    await card('%3').locator('.message-form textarea').click();
    await page.waitForFunction(() => getSelection().isCollapsed);
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Live');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .output').textContent.endsWith('1'));
    assert(await card('%3').locator('.explain').isDisabled());
    assert.equal(await card('%3').locator('.selection-note').textContent(), '');
    await selectFirstLine();
    await selectableOutput.click({position: {x: 16, y: 16}});
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Live');
    await selectFirstLine();
    await clearSelection('%3');
    await selectFirstLine();
    await card('%3').locator('h2').evaluate(el => {
      const range = document.createRange(); range.selectNodeContents(el);
      getSelection().removeAllRanges(); getSelection().addRange(range);
    });
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Live');
    assert.equal(await page.evaluate(() => cards.get('%3:first:%3').selected), '');
    await page.evaluate(() => getSelection().removeAllRanges());
    await selectFirstLine();
    const selectedKeyCount = keyCount;
    await selectableOutput.press('Escape');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Live');
    assert.equal(await page.evaluate(() => getSelection().rangeCount), 0);
    assert.equal(await page.evaluate(() => cards.get('%3:first:%3').selected), '');
    assert.equal(keyCount, selectedKeyCount, 'Selected Escape stays in the browser');
    await selectableOutput.press('Escape');
    await page.waitForFunction(() => !cards.get('%3:first:%3').busy);
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Escape'});
    assert.equal(keyCount, selectedKeyCount + 1, 'Unselected Escape reaches the agent');
    await selectFirstLine();
    keyDelay = 1000;
    await selectableOutput.press('ArrowDown');
    await page.waitForFunction(() => cards.get('%3:first:%3').busy);
    const busySelectionKeyCount = keyCount;
    await selectableOutput.press('Escape');
    assert.equal(await card('%3').locator('.state').textContent(), 'Live');
    assert.equal(await page.evaluate(() => getSelection().rangeCount), 0);
    assert.equal(keyCount, busySelectionKeyCount, 'Busy selected Escape stays in the browser');
    await checkTabFocus('%3');
    await page.waitForFunction(() => !cards.get('%3:first:%3').busy);
    keyDelay = 0;
    await card('%3').locator('.output').press('ArrowDown');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Key sent');
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Down'});
    await card('%3').locator('.output').press('Backspace');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Key sent' && !document.querySelector('.pane:not([hidden]) .keys-toggle').disabled);
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Backspace'});
    const controlKeyCount = keyCount;
    await card('%3').locator('.output').press('1');
    await card('%3').locator('.output').press('y');
    assert.equal(keyCount, controlKeyCount);
    const colors = await card('%3').locator('.output').evaluate(el => ({
      bg: getComputedStyle(el).backgroundColor, fg: getComputedStyle(el).color,
      spans: [...el.querySelectorAll('span')].slice(0, 8).map(span => ({text: span.textContent, fg: getComputedStyle(span).color, bg: getComputedStyle(span).backgroundColor, bold: getComputedStyle(span).fontWeight, italic: getComputedStyle(span).fontStyle}))
    }));
    assert.equal(colors.bg, 'rgb(18, 52, 86)'); assert.equal(colors.fg, 'rgb(171, 205, 239)');
    assert.equal(colors.spans[0].fg, 'rgb(200, 30, 40)'); assert.equal(colors.spans[1].fg, 'rgb(0, 255, 0)'); assert.equal(colors.spans[1].bg, 'rgb(10, 20, 30)');
    assert(colors.spans.some(span => span.text === 'Bright' && span.fg === 'rgb(255, 0, 0)'));
    assert(colors.spans.some(span => span.text === 'Blue bg' && span.bg === 'rgb(0, 0, 95)'));
    assert(colors.spans.some(span => span.text === 'Colon RGB' && span.fg === 'rgb(1, 2, 3)'));
    assert(colors.spans.some(span => span.text === 'Style' && span.bold === '700' && span.italic === 'italic'));
    assert.equal(await card('%3').locator('script').count(), 0);
    const widths = await card('%3').evaluate(el => [el.getBoundingClientRect().width, el.parentElement.getBoundingClientRect().width]);
    assert.equal(widths[0], widths[1]);
    assert(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight));
    assert(await card('%3').locator('.output').evaluate(el => el.getBoundingClientRect().height > innerHeight * 0.65));
    const resized = await card('%3').evaluate(el => {
      const textarea = el.querySelector('.message-form textarea'); const original = textarea.style.height;
      textarea.style.height = '10000px';
      const result = {
        outputHeight: el.querySelector('.output').getBoundingClientRect().height,
        controlsVisible: ['.message-form textarea', '.message-form button', '.feedback'].every(selector => {
          const rect = el.querySelector(selector).getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight;
        })
      };
      textarea.style.height = original; return result;
    });
    assert(resized.outputHeight > 0); assert(resized.controlsVisible);
    assert.deepEqual(await page.evaluate(() => {
      const pane = {screen: '› Typed', styledScreen: '› Typed\n', output: 'Joined history', cursorY: 0, menu: false};
      return [inputBox({...pane, cursorY: -1}), inputBox({...pane, cursorY: 99}), inputBox({...pane, cursorY: '0'}), inputBox({...pane, screen: 'Prose › Typed'}), inputBox({...pane, styledScreen: '› Different\n'})];
    }), ['', '', '', '', '']);
    menu['%5'] = '\nHistorical › marker\n  › Typed input\nWrapped output rowcontinued row\n';
    screen['%5'] = '  › Typed input\nWrapped output row\ncontinued row\n'; cursorY['%5'] = 0;
    await paneTab('%5').click();
    await checkTabFocus('%5');
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%5"] .output').textContent.endsWith('Wrapped output rowcontinued row\n'));
    assert.equal(await page.evaluate(() => inputBox(cards.get('%5:first:%5').latest)), 'Typed input');
    assert.equal(await paneTab('%5').evaluate(el => el.classList.contains('needs-answer')), false);
    await page.waitForFunction(() => document.querySelector('#agents [data-key="%5:first:%5"]').getAttribute('aria-label')?.endsWith(', text waiting in the box'));
    assert((await sessionTab('alpha').getAttribute('aria-label')).endsWith(', text waiting in the box'));
    await paneTab('%5').click();
    assert(await paneTab('%5').evaluate(el => el.classList.contains('needs-answer')));
    revision['%5']++;
    await page.waitForFunction(() => !document.querySelector('#agents [data-key="%5:first:%5"]').classList.contains('needs-answer'));
    assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('needs-answer')), false);
    await page.waitForFunction(() => document.querySelector('#agents [data-key="%5:first:%5"]').classList.contains('needs-answer'));
    menuShown['%5'] = true;
    await page.waitForFunction(() => document.querySelector('#agents [data-key="%5:first:%5"]').getAttribute('aria-label')?.endsWith(', waiting for an answer'));
    assert((await sessionTab('alpha').getAttribute('aria-label')).endsWith(', waiting for an answer'));
    menuShown['%5'] = false;
    menu['%5'] = '\n  › \n\n'; screen['%5'] = '  › \n\n';
    await page.waitForFunction(() => !document.querySelector('#agents [data-key="%5:first:%5"]').classList.contains('needs-answer'));
    assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('needs-answer')), false);
    for (const [name, style] of [['dim', '\x1b[2m'], ['gray', '\x1b[38;5;242m']]) {
      menu['%5'] = '\n  › ' + style + name + ' hintcontinued hint\x1b[0m\n\n';
      screen['%5'] = '  › ' + name + ' hint\ncontinued hint\n\n';
      styledScreen['%5'] = '  › ' + style + name + ' hint\ncontinued hint\x1b[0m\n\n';
      await page.waitForFunction(label => document.querySelector('.pane[data-pane="%5"] .key-shortcuts').textContent === 'Tab: ' + label, name + ' hint');
      await page.waitForTimeout(1400);
      assert.equal(await paneTab('%5').evaluate(el => el.classList.contains('needs-answer')), false);
      assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('needs-answer')), false);
    }
    cursorY['%5'] = -1; menu['%5'] = ''; screen['%5'] = ''; delete styledScreen['%5'];
    await paneTab('%3').click();
    menu['%5'] = '\n\x1b[31m❯\x1b[0m 1. Accept';
    screen['%5'] = '  1. Prose example\n  2. Another example\n\n❯ 1. Accept\n  2. ' + 'Long menu label '.repeat(5) + '\n';
    menuShown['%5'] = true;
    await page.waitForSelector('#agents [data-key="%5:first:%5"].needs-answer');
    assert(await sessionTab('alpha').evaluate(el => el.classList.contains('needs-answer')));
    assert((await paneTab('%5').getAttribute('aria-label')).endsWith(', waiting for an answer'));
    await paneTab('%5').click();
    assert(await paneTab('%5').evaluate(el => el.classList.contains('needs-answer')));
    const shortcuts = card('%5').locator('.key-shortcuts button');
    assert.deepEqual(await shortcuts.allTextContents(), ['Up', 'Down', 'Enter', 'Esc']);
    assert.equal(await card('%5').locator('.keys-toggle').getAttribute('aria-expanded'), 'false');
    assert.equal(await card('%5').locator('.keys-toggle').evaluate(el => getComputedStyle(el, '::after').content), '" ▸" / ""');
    const closedToggleBackground = await card('%5').locator('.keys-toggle').evaluate(el => getComputedStyle(el).backgroundColor);
    assert(await card('%5').locator('.key-shortcuts').evaluate(el => el.previousElementSibling.className === 'key-buttons'));
    await card('%5').locator('.keys-toggle').click();
    assert.equal(await card('%5').locator('.keys-toggle').evaluate(el => getComputedStyle(el, '::after').content), '" ▾" / ""');
    assert.notEqual(await card('%5').locator('.keys-toggle').evaluate(el => getComputedStyle(el).backgroundColor), closedToggleBackground);
    assert.deepEqual(await card('%5').locator('.keys button:visible').allTextContents(), ['Keys', 'Tab', ...await shortcuts.allTextContents()]);
    for (const key of ['Up', 'Down', 'Enter', 'Escape']) assert.equal(await card('%5').locator(`.keys button[data-key="${key}"]:visible`).count(), 1);
    assert(await card('%5').locator('.keys button[data-key]').evaluateAll(buttons => buttons.every(button => ['Tab', 'Up', 'Down', 'Enter', 'Escape', 'Backspace'].includes(button.dataset.key))));
    const menuKeyCount = keyCount, menuMessageCount = sent.length;
    await card('%5').locator('.message-form textarea').fill(' \n'); await card('%5').locator('.message-form button').click();
    await card('%5').locator('.message-form textarea').fill(''); await card('%5').locator('.message-form textarea').press('Shift+Enter');
    await page.waitForTimeout(350);
    assert.equal(keyCount, menuKeyCount); assert.equal(sent.length, menuMessageCount);
    await card('%5').locator('.key-shortcuts button[data-key="Enter"]').click();
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%5"] .feedback').textContent === 'Pressed Enter');
    assert.deepEqual(keyRequest, {pane: '%5', identity: 'first:%5', key: 'Enter'});
    assert.equal(keyCount, menuKeyCount + 1);
    await card('%5').locator('.message-form textarea').fill('Keep the shortcut draft');
    await card('%5').locator('.output').evaluate(el => {
      const node = el.querySelector('span').firstChild, range = document.createRange();
      range.setStart(node, 0); range.setEnd(node, 4);
      getSelection().removeAllRanges(); getSelection().addRange(range);
    });
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%5"] .state').textContent === 'Paused');
    keyDelay = 500;
    await shortcuts.first().click();
    await page.waitForFunction(() => [...document.querySelectorAll('.pane[data-pane="%5"] .keys button')].every(button => button.disabled));
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%5"] .feedback').textContent === 'Key sent');
    assert.deepEqual(keyRequest, {pane: '%5', identity: 'first:%5', key: 'Up'});
    assert.equal(await card('%5').locator('.message-form textarea').inputValue(), 'Keep the shortcut draft');
    assert.equal(await page.evaluate(() => getSelection().toString()), "It's");
    await clearSelection('%5');
    await card('%5').locator('.message-form textarea').fill('');
    keyDelay = 0;
    for (const menuScreen of [
      '❯ 1. Yes\n  2. No\n  3. Type something.\n',
      '  1. Yes\n  2. No\n❯ 3. Type something.\n',
      '  1. Yes\n  2. No\n❯ 3. 42333\n',
      '› Yes, proceed (y)\n  Yes, allow this command (a)\n  No, stop (n)\n',
      'Enter to confirm']) {
      screen['%5'] = menuScreen; cursorY['%5'] = 0; menu['%5'] = '\n' + menuScreen;
      await page.waitForFunction(text => document.querySelector('.pane[data-pane="%5"] .output').textContent.endsWith(text), menuScreen);
      assert.deepEqual(await shortcuts.allTextContents(), ['Up', 'Down', 'Enter', 'Esc']);
      assert.deepEqual(await card('%5').locator('.keys button:visible').allTextContents(), ['Keys', 'Tab', 'Up', 'Down', 'Enter', 'Esc']);
      for (const key of ['Up', 'Down', 'Enter', 'Escape']) assert.equal(await card('%5').locator('.keys button[data-key="' + key + '"]:visible').count(), 1);
    }
    menu['%5'] += '\n' + 'Answered\n'.repeat(6);
    menuShown['%5'] = false;
    screen['%5'] = 'Answered\n';
    await page.waitForFunction(() => !document.querySelector('#agents [data-key="%5:first:%5"]').classList.contains('needs-answer'));
    assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('needs-answer')), false);
    assert((await card('%5').locator('.output').textContent()).includes('Enter to confirm'));
    assert.equal(await shortcuts.count(), 0);
    assert.deepEqual(await card('%5').locator('.keys button:visible').allTextContents(), ['Keys', 'Up', 'Down', 'Tab', 'Enter', 'Esc', 'Backspace']);
    const backspace = card('%5').locator('.key-buttons button[data-key="Backspace"]');
    const clickKeyCount = keyCount;
    await backspace.click();
    await page.waitForFunction(() => !document.querySelector('.pane[data-pane="%5"] button[data-key="Backspace"]').disabled);
    await page.waitForTimeout(500);
    assert.equal(keyCount, clickKeyCount + 1, 'Backspace click sends exactly once');
    assert.deepEqual(keyRequest, {pane: '%5', identity: 'first:%5', key: 'Backspace'});
    await backspace.press('Enter');
    await page.waitForFunction(() => !document.querySelector('.pane[data-pane="%5"] button[data-key="Backspace"]').disabled);
    assert.equal(keyCount, clickKeyCount + 2, 'Backspace keeps keyboard activation');
    const busyKeyCount = keyCount;
    keyDelay = 600;
    await backspace.hover(); await page.mouse.down();
    await page.waitForFunction(() => cards.get('%5:first:%5').busy && document.querySelector('.pane[data-pane="%5"] button[data-key="Backspace"]').getAttribute('aria-disabled') === 'true');
    await page.waitForTimeout(200);
    assert.equal(keyCount, busyKeyCount + 1, 'Hold drops repeat ticks while busy');
    assert.equal(await backspace.evaluate(el => el.disabled), false, 'Held Backspace stays physically enabled');
    await page.mouse.up();
    assert.equal(await backspace.evaluate(el => el.disabled), true, 'Release restores busy disabled state');
    await page.waitForFunction(() => !document.querySelector('.pane[data-pane="%5"] button[data-key="Backspace"]').disabled);
    await page.waitForTimeout(500);
    assert.equal(keyCount, busyKeyCount + 1, 'Release while busy stops repeat');
    keyDelay = 0;
    const holdKeyCount = keyCount;
    await backspace.hover(); await page.mouse.down();
    await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
    await page.waitForTimeout(650);
    await page.waitForFunction(() => !cards.get('%5:first:%5').busy);
    const releasedKeyCount = keyCount;
    await page.mouse.up();
    assert(releasedKeyCount > holdKeyCount + 1, 'Backspace hold sends multiple keys');
    await page.waitForTimeout(200);
    assert.equal(keyCount, releasedKeyCount, 'Release stops repeat without a trailing click');
    keyDelay = 600;
    const blurKeyCount = keyCount;
    await backspace.hover(); await page.mouse.down();
    await page.waitForFunction(() => cards.get('%5:first:%5').busy);
    assert.equal(await backspace.evaluate(el => el.disabled), false);
    await page.evaluate(() => window.dispatchEvent(new Event('blur')));
    assert.equal(await backspace.evaluate(el => el.disabled), true, 'Blur restores busy disabled state');
    await page.waitForFunction(() => !cards.get('%5:first:%5').busy);
    await page.waitForTimeout(200);
    assert.equal(keyCount, blurKeyCount + 1, 'Blur during hold stops repeat after the in-flight request');
    await page.mouse.up();
    keyDelay = 0;
    await paneTab('%3').click();
    menu['%3'] = '\n❯ \x1b[2m' + 'Try a hint '.repeat(10) + '\x1b[22m';
    screen['%3'] = '❯ ' + 'Try a hint '.repeat(10);
    styledScreen['%3'] = menu['%3'].slice(1);
    const hintChip = card('%3').locator('.key-shortcuts button[data-key="Tab"]');
    await hintChip.waitFor();
    assert((await hintChip.textContent()).startsWith('Tab: Try a hint'));
    assert.equal((await hintChip.textContent()).length, 60);
    await card('%3').locator('.keys-toggle').click();
    assert.equal(await card('%3').locator('.keys button[data-key="Tab"]:visible').count(), 1);
    assert.deepEqual(await card('%3').locator('.keys button:visible').allTextContents(), ['Keys', 'Up', 'Down', 'Enter', 'Esc', 'Backspace', await hintChip.textContent()]);
    await hintChip.click();
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .feedback').textContent === 'Key sent');
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Tab'});
    menu['%3'] = '\n› \x1b[38;5;242mGray hint\x1b[39m'; screen['%3'] = '› Gray hint';
    styledScreen['%3'] = menu['%3'].slice(1);
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .key-shortcuts').textContent === 'Tab: Gray hint');
    menu['%3'] += '\n› typed text'; screen['%3'] = '› typed text';
    styledScreen['%3'] = screen['%3'];
    await page.waitForFunction(() => !document.querySelector('.pane[data-pane="%3"] .key-shortcuts button'));
    assert(await card('%3').locator('.key-buttons button[data-key="Tab"]').isVisible());
    menu['%3'] = ''; screen['%3'] = ''; delete styledScreen['%3'];
    for (const id of ['%5', '%2', '%9', '%10']) revision[id] = 1;
    revision['%3'] = 1;
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .output').textContent.endsWith('1'));
    for (const id of ['%5', '%2']) assert.equal(await paneTab(id).evaluate(el => el.classList.contains('unread')), false);
    for (const name of ['alpha', 'zeta']) assert.equal(await sessionTab(name).evaluate(el => el.classList.contains('unread')), false);
    await sessionTab('zeta').click();
    for (const id of ['%9', '%10']) assert.equal(await paneTab(id).evaluate(el => el.classList.contains('unread')), false);
    await paneTab('%10').click(); await sessionTab('alpha').click(); await paneTab('%5').click();
    await paneTab('%3').focus(); revision['%3'] = 2; revision['%8'] = 1;
    await page.waitForSelector('#agents [data-key="%3:first:%3"].unread');
    assert.equal(await page.evaluate(() => document.activeElement.dataset.key), '%3:first:%3');
    assert(await sessionTab('alpha').evaluate(el => el.classList.contains('unread')));
    assert(await sessionTab('zeta').evaluate(el => el.classList.contains('unread')));
    await paneTab('%3').click(); assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('unread')), false);
    await page.locator('#right-click').uncheck(); await selectFirstLine();
    assert.equal(await page.evaluate(() => getSelection().toString()), firstLine);
    const frozen = await card('%3').locator('.output').textContent(); revision['%3'] = 3;
    await page.waitForTimeout(1400);
    assert.equal(await card('%3').locator('.output').textContent(), frozen);
    assert.equal(await page.evaluate(() => getSelection().toString()), firstLine);
    await card('%3').locator('.output').click({button: 'right', position: {x: 24, y: 24}}); assert.equal(sent.length, 0);
    await card('%3').locator('.explain').click();
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'target box busy');
    assert.deepEqual(sent[0], {pane: '%3', identity: 'first:%3', text: firstLine});
    blocked = false; await card('%3').locator('.explain').click();
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Explained');
    assert.deepEqual(sent[1], {pane: '%3', identity: 'first:%3', text: firstLine});
    assert.equal(await card('%3').locator('.state').textContent(), 'Live');
    assert(await card('%3').locator('.explain').isDisabled());
    await page.locator('#right-click').check(); await selectFirstLine();
    await card('%3').locator('.output').click({button: 'right', position: {x: 24, y: 24}});
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Live');
    assert.deepEqual(sent[2], {pane: '%3', identity: 'first:%3', text: firstLine});
    explainDelay = 300;
    await selectFirstLine(); await card('%3').locator('.explain').click();
    await card('%3').locator('.output').evaluate(el => {
      const node = el.querySelector('span').firstChild; const range = document.createRange();
      range.setStart(node, 0); range.setEnd(node, 4);
      getSelection().removeAllRanges(); getSelection().addRange(range);
    });
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Explained');
    assert.equal(await page.evaluate(() => getSelection().toString()), "It's");
    assert.equal(await card('%3').locator('.state').textContent(), 'Paused');
    assert(await card('%3').locator('.explain').isEnabled());
    await clearSelection('%3');
    async function selectRepeatedLine(second) {
      await card('%3').locator('.output').evaluate((el, second) => {
        const text = 'A line of agent output.';
        const node = [...el.querySelectorAll('span')].find(span => span.textContent.includes(text)).firstChild;
        const first = node.textContent.indexOf(text);
        const start = second ? node.textContent.indexOf(text, first + text.length) : first;
        const range = document.createRange(); range.setStart(node, start); range.setEnd(node, start + text.length);
        getSelection().removeAllRanges(); getSelection().addRange(range);
      }, second);
    }
    await selectRepeatedLine(false);
    await page.waitForFunction(() => !document.querySelector('.pane:not([hidden]) .explain').disabled);
    await card('%3').locator('.explain').click();
    await selectRepeatedLine(true);
    const repeatedStart = await page.evaluate(() => getSelection().getRangeAt(0).startOffset);
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Explained');
    assert.equal(await page.evaluate(() => getSelection().toString()), 'A line of agent output.');
    assert.equal(await page.evaluate(() => getSelection().getRangeAt(0).startOffset), repeatedStart);
    assert.equal(await card('%3').locator('.state').textContent(), 'Paused');
    await clearSelection('%3');
    await selectFirstLine(); await card('%3').locator('.explain').click();
    await paneTab('%2').click();
    await card('%2').locator('.output').evaluate(el => {
      const node = el.querySelector('span').firstChild; const range = document.createRange();
      range.setStart(node, 0); range.setEnd(node, 4);
      getSelection().removeAllRanges(); getSelection().addRange(range);
    });
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .feedback').textContent === 'Explained');
    assert.equal(await page.evaluate(() => getSelection().toString()), "It's");
    assert.equal(await card('%2').locator('.state').textContent(), 'Paused');
    assert.equal(await card('%3').locator('.state').textContent(), 'Live');
    await clearSelection('%2'); await paneTab('%3').click(); explainDelay = 0;
    const summary = promptButton('%3', 'Code summary');
    assert(await summary.isEnabled());
    await card('%3').locator('.message-form textarea').fill('Keep summary draft');
    await selectFirstLine();
    blocked = true;
    await summary.click();
    assert(await summary.isDisabled());
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'target box busy' && !document.querySelector('.pane:not([hidden]) .prompt-buttons button').disabled);
    blocked = false;
    await summary.click();
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Message sent' && !document.querySelector('.pane:not([hidden]) .prompt-buttons button').disabled);
    assert.deepEqual(sent[sent.length - 1], {pane: '%3', identity: 'first:%3', text: 'Summarize the code changes on this branch: diff against the base branch (main, or master if main is absent) plus uncommitted changes, grouped by file, what changed and why, short.'});
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'Keep summary draft');
    assert.equal(await card('%3').locator('.state').textContent(), 'Paused');
    const addedButton = {name: 'Review changes', description: 'Check each changed file.', prompt: 'Review these changes.\nExplain each risk.'};
    const buttonForm = card('%3').locator('.button-form');
    await card('%3').locator('.add-button').click();
    const rows = await card('%3').evaluate(el => ['.output', '.actions', '.button-form', '.keys', '.message-form', '.feedback'].map(selector => {
      const rect = el.querySelector(selector).getBoundingClientRect(); return {top: rect.top, bottom: rect.bottom};
    }));
    assert(rows.every((rect, index) => !index || rect.top >= rows[index - 1].bottom), 'Visual rows keep their order');
    await buttonForm.getByRole('button', {name: 'Cancel', exact: true}).click();
    assert(await buttonForm.isHidden());
    await card('%3').locator('.add-button').click();
    for (const [name, value] of Object.entries(addedButton)) await buttonForm.locator('[name="' + name + '"]').fill(value);
    await buttonForm.getByRole('button', {name: 'Save', exact: true}).click();
    await buttonForm.waitFor({state: 'hidden'});
    assert.deepEqual(createdButtons, [addedButton]);
    for (const pane of roles) {
      assert.equal(await promptButton(pane.id, addedButton.name).count(), 1);
      assert.equal(await promptButton(pane.id, addedButton.name).getAttribute('title'), addedButton.description);
    }
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'Keep summary draft');
    assert.equal(await card('%3').locator('.state').textContent(), 'Live');
    await card('%3').locator('.add-button').click();
    const buttonDraft = {name: 'Unsaved button', description: 'Keep this description.', prompt: 'Keep this prompt.'};
    for (const [name, value] of Object.entries(buttonDraft)) await buttonForm.locator('[name="' + name + '"]').fill(value);
    const unchangedButton = await summary.elementHandle();
    const unchangedResponse = await page.waitForResponse(response => new URL(response.url()).pathname === '/api/buttons' && response.request().method() === 'GET');
    await unchangedResponse.finished();
    assert(await unchangedButton.evaluate(el => el.isConnected), 'Unchanged poll keeps button DOM');
    const handAdded = {name: 'Hand added', description: 'Added outside the browser.', prompt: 'Explain this file.'};
    buttons.push(handAdded); buttons.sort((a, b) => a.name.localeCompare(b.name));
    await promptButton('%3', handAdded.name).waitFor();
    for (const pane of roles) assert.equal(await promptButton(pane.id, handAdded.name).count(), 1);
    const feedbackBeforePollError = await card('%3').locator('.feedback').textContent();
    buttons.splice(buttons.indexOf(handAdded), 1);
    buttonError = 'Button list unavailable';
    await page.waitForFunction(() => document.querySelector('#connection').textContent === 'Button list unavailable');
    assert.equal(await card('%3').locator('.feedback').textContent(), feedbackBeforePollError);
    for (const pane of roles) assert.equal(await promptButton(pane.id, handAdded.name).count(), 1);
    buttonError = null;
    await promptButton('%3', handAdded.name).waitFor({state: 'detached'});
    for (const pane of roles) assert.equal(await promptButton(pane.id, handAdded.name).count(), 0);
    assert.equal(await card('%3').locator('.feedback').textContent(), feedbackBeforePollError);
    for (const [name, value] of Object.entries(buttonDraft)) assert.equal(await buttonForm.locator('[name="' + name + '"]').inputValue(), value);
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'Keep summary draft');
    assert.equal(await page.evaluate(() => cards.get('%3:first:%3').selected), '');
    assert.equal(await card('%3').locator('.state').textContent(), 'Live');
    await buttonForm.getByRole('button', {name: 'Cancel', exact: true}).click();
    await clearSelection('%3');
    const commitPrompt = 'Commit all changes in this repository with a descriptive commit message. Do not push.';
    const pushPrompt = 'Push committed work to the remote. If the working tree has uncommitted changes, first commit them all with a descriptive commit message, then push. Push the current branch to its upstream, never force-push.';
    await paneTab('%5').click();
    for (const [name, prompt, busy] of [['Commit all', commitPrompt, true], ['Commit all', commitPrompt, false], ['Push all', pushPrompt, false]]) {
      blocked = busy;
      await promptButton('%5', name).click();
      assert(await card('%5').locator('.prompt-buttons button').evaluateAll(buttons => buttons.every(button => button.disabled)));
      await page.waitForFunction(text => document.querySelector('.pane[data-pane="%5"] .feedback').textContent === text && !document.querySelector('.pane[data-pane="%5"] .prompt-buttons button').disabled, busy ? 'target box busy' : 'Message sent');
      assert.deepEqual(sent[sent.length - 1], {pane: '%5', identity: 'first:%5', text: prompt});
      assert(await card('%5').isVisible());
    }
    await sessionTab('zeta').click();
    await paneTab('%10').click();
    await promptButton('%10', 'Push all').click();
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%10"] .feedback').textContent === 'Message sent' && !document.querySelector('.pane[data-pane="%10"] .prompt-buttons button').disabled);
    assert.deepEqual(sent[sent.length - 1], {pane: '%10', identity: 'first:%10', text: pushPrompt});
    assert(await card('%10').isVisible());
    await sessionTab('alpha').click();
    await paneTab('%3').click();
    const messageBox = card('%3').locator('.message-form textarea'); const keyboardStart = sent.length;
    assert.equal(await messageBox.getAttribute('placeholder'), 'Ask this agent something… (Shift+Enter to send)');
    await messageBox.fill('Keyboard message'); await messageBox.press('Shift+Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .message-form textarea').value === '');
    assert.equal(sent.length, keyboardStart + 1);
    assert.deepEqual(sent[keyboardStart], {pane: '%3', identity: 'first:%3', text: 'Keyboard message', append: true});
    await messageBox.fill('First line'); await messageBox.press('Enter');
    assert.equal(await messageBox.inputValue(), 'First line\n');
    assert(await messageBox.evaluate(el => el.dispatchEvent(new KeyboardEvent('keydown', {key: 'Enter', shiftKey: true, isComposing: true, bubbles: true, cancelable: true}))));
    await page.waitForTimeout(350); assert.equal(sent.length, keyboardStart + 1);
    assert.equal(await page.locator('.append, .append-action').count(), 0);
    sendError = 'target input box holds typed text';
    const message = "It's `quoted`\n日本語";
    await messageBox.fill(message); await messageBox.press('Shift+Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'target input box holds typed text');
    assert.deepEqual(sent[sent.length - 1], {pane: '%3', identity: 'first:%3', text: message, append: true});
    assert.equal(await messageBox.inputValue(), message);
    sendError = null;
    await messageBox.fill('Changed append draft'); await messageBox.press('Shift+Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .message-form textarea').value === '');
    assert.deepEqual(sent[sent.length - 1], {pane: '%3', identity: 'first:%3', text: 'Changed append draft', append: true});
    await messageBox.fill('Next message'); await messageBox.press('Shift+Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .message-form textarea').value === '');
    assert.deepEqual(sent[sent.length - 1], {pane: '%3', identity: 'first:%3', text: 'Next message', append: true});
    const messageCount = sent.length;
    keyDelay = 300;
    await messageBox.fill(' \n\t'); await card('%3').locator('.message-form button').click();
    assert(await card('%3').locator('.message-form button').isDisabled());
    await messageBox.fill('Draft during Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Pressed Enter');
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Enter'});
    assert.equal(await messageBox.inputValue(), 'Draft during Enter');
    keyDelay = 0;
    await messageBox.fill(''); await messageBox.press('Shift+Enter');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Pressed Enter');
    assert.deepEqual(keyRequest, {pane: '%3', identity: 'first:%3', key: 'Enter'});
    assert.equal(sent.length, messageCount);
    await card('%3').locator('.message-form textarea').fill('Original message'); await card('%3').locator('.message-form button').click();
    await card('%3').locator('.message-form textarea').fill('New draft');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Message sent');
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'New draft');
    await card('%3').locator('.message-form textarea').fill('Repeat'); await card('%3').locator('.message-form button').click();
    await card('%3').locator('.message-form textarea').fill('Other'); await card('%3').locator('.message-form textarea').fill('Repeat');
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Message sent');
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'Repeat');
    await card('%3').locator('.message-form textarea').fill('New draft');
    await sessionTab('zeta').click(); assert(await card('%10').isVisible());
    assert.equal(await page.locator('#project-path').textContent(), 'Folder: /work/zeta project');
    assert(await paneTab('%8').evaluate(el => el.classList.contains('unread')));
    await paneTab('%8').click(); assert.equal(await sessionTab('zeta').evaluate(el => el.classList.contains('unread')), false);
    assert(await card('%8').locator('.output').evaluate(el => el.scrollTop > 0));
    await sessionTab('alpha').click(); assert(await card('%3').isVisible());
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'New draft');
    await paneTab('%5').click(); assert.equal(await sessionTab('alpha').evaluate(el => el.classList.contains('unread')), false);
    await paneTab('%3').click(); await selectFirstLine();
    await paneTab('%2').click(); await paneTab('%3').click();
    assert.equal(await card('%3').locator('.state').textContent(), 'Paused');
    await clearSelection('%3');
    joinedHistory = true;
    const historyOutput = card('%3').locator('.output');
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .output').textContent.startsWith('Logical 40 '));
    const wideHeight = await historyOutput.evaluate(el => el.scrollHeight);
    assert(await historyOutput.evaluate(el => el.scrollWidth <= el.clientWidth));
    await page.setViewportSize({width: 900, height: 950});
    assert(await historyOutput.evaluate(el => el.scrollWidth <= el.clientWidth));
    assert(await historyOutput.evaluate((el, height) => el.scrollHeight > height, wideHeight));
    await page.setViewportSize({width: 1440, height: 950});
    for (const [lines, first] of [[2000, 20], [3000, 0]]) {
      await historyOutput.evaluate(el => { el.scrollTop = 300; });
      await page.waitForFunction(() => cards.get('%3:first:%3').scrollTop === 300);
      await historyOutput.evaluate(el => { el.scrollTop = 100; });
      await page.waitForFunction(first => document.querySelector('.pane[data-pane="%3"] .output').textContent.startsWith('Logical ' + first + ' '), first);
      assert(historyRequests.some(request => request.pane === '%3' && request.lines === lines));
    }
    assert.deepEqual(await page.evaluate(() => {
      const current = cards.get('%3:first:%3');
      return [current.lines, current.latest.capturedLines, current.fullHistory, current.el.querySelector('.output').textContent.split('\n').length];
    }), [3000, 3000, true, 60]);
    joinedHistory = false;
    await page.waitForFunction(() => document.querySelector('.pane[data-pane="%3"] .output').textContent.startsWith("It's quoted"));
    await historyOutput.evaluate(el => { el.scrollTop = el.scrollHeight; });
    await page.waitForFunction(() => cards.get('%3:first:%3').lines === 1000);
    await card('%3').locator('.output').evaluate(el => { el.scrollTop = 0; });
    await card('%3').locator('.output').hover(); await page.mouse.wheel(0, 200);
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .output').scrollTop > 0);
    await page.screenshot({path: '/tmp/peon-code-web-desktop.png', fullPage: true});
    await page.reload(); await page.waitForSelector('.pane:not([hidden])');
    await page.locator('.brand').click(); await page.waitForSelector('.pane:not([hidden])');
    await page.setViewportSize({width: 375, height: 812});
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path: '/tmp/peon-code-web-mobile.png', fullPage: true});
    assert.equal(await page.locator('.top-links a').count(), 3);
    await card('%3').locator('.message-form textarea').fill('Keep this draft');
    await selectFirstLine();
    menu['%3'] = '\n❯ \x1b[2mHint\x1b[0m\n  2. Other'; screen['%3'] = '❯ Hint\n  2. Other'; menuShown['%3'] = true;
    styledScreen['%3'] = menu['%3'].slice(1);
    await card('%3').locator('.key-shortcuts button[data-key="Tab"]').waitFor();
    await card('%3').locator('.keys-toggle').click();
    assert.deepEqual(await card('%3').locator('.keys button:visible').allTextContents(), ['Keys', 'Up', 'Down', 'Enter', 'Esc', 'Tab: Hint']);
    empty = true;
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .state').textContent === 'Closed');
    assert.equal(await card('%3').locator('.message-form textarea').inputValue(), 'Keep this draft');
    assert(await card('%3').locator('.explain').isDisabled());
    assert(await summary.isDisabled());
    assert(await card('%3').locator('.prompt-buttons button').evaluateAll(buttons => buttons.every(button => button.disabled)));
    assert(await card('%3').locator('.add-button').isDisabled());
    assert(await card('%3').locator('.message-form button').isDisabled());
    assert(await card('%3').locator('.keys button').evaluateAll(buttons => buttons.every(button => button.disabled)));
    assert.equal(await card('%3').locator('.keys-toggle').getAttribute('aria-expanded'), 'true');
    assert.deepEqual(await card('%3').locator('.keys button:visible').allTextContents(), ['Keys', 'Up', 'Down', 'Enter', 'Esc', 'Tab: Hint']);
    assert.equal(await paneTab('%3').textContent(), 'Boss · manager · closed');
    await card('%3').locator('.message-form textarea').fill('');
    await card('%3').locator('.output').click({position: {x: 24, y: 24}});
    await page.waitForFunction(() => getSelection().isCollapsed);
    await page.evaluate(() => { document.querySelector('#connection').textContent = 'Waiting refresh'; });
    await page.waitForFunction(() => document.querySelector('#connection').textContent === '0 agents connected');
    assert.equal(await card('%3').count(), 1);
    assert.deepEqual(await page.evaluate(() => {
      const closed = cards.get('%3:first:%3');
      return [closed.selected, closed.busy, closed.el.querySelector('.message-form textarea').value];
    }), [firstLine, false, '']);
    const closedKeyCount = keyCount;
    await card('%3').locator('.output').press('Escape');
    assert.equal(await page.evaluate(() => cards.get('%3:first:%3').selected), firstLine);
    assert.equal(keyCount, closedKeyCount, 'Closed Escape keeps saved text');
    await checkTabFocus('%3');
    assert.equal(await page.evaluate(() => cards.get('%3:first:%3').selected), firstLine);
    await card('%3').locator('.message-form textarea').fill('Keep this draft');
    const deliveries = sent.length;
    await card('%3').locator('.output').click({button: 'right'});
    assert.equal(sent.length, deliveries);
    empty = false;
    roles.splice(0, roles.length, {id: '%3', identity: 'restarted:%3', name: 'New boss', role: 'manager', session: 'alpha'});
    const oldCard = page.locator('.pane[data-key="%3:first:%3"]');
    const newCard = page.locator('.pane[data-key="%3:restarted:%3"]');
    await page.waitForSelector('.pane[data-key="%3:restarted:%3"]', {state: 'attached'});
    assert.equal(await oldCard.locator('.message-form textarea').inputValue(), 'Keep this draft');
    assert.equal(await oldCard.locator('h2').textContent(), 'Boss');
    assert(await oldCard.locator('.explain').isDisabled());
    await paneTab('%3').click();
    assert(await newCard.isVisible());
    assert.equal(await newCard.locator('.message-form textarea').inputValue(), '');
    assert(await newCard.locator('.explain').isDisabled());
    await newCard.locator('.message-form textarea').fill('New agent message');
    await newCard.locator('.message-form button').click();
    await page.waitForFunction(() => document.querySelector('.pane:not([hidden]) .feedback').textContent === 'Message sent');
    assert.deepEqual(sent[sent.length - 1], {pane: '%3', identity: 'restarted:%3', text: 'New agent message', append: true});
    await page.locator('#agents [data-key="%3:first:%3"]').click();
    await oldCard.locator('.discard').click();
    assert.equal(await oldCard.count(), 0);
    assert(await newCard.isVisible());
    empty = true;
    await page.waitForFunction(() => !document.querySelector('#empty').hidden);
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('browser: PASS (sessions, dismiss status, prompt buttons, create button, button polling, unchanged button DOM, button deletion, poll error recovery, selection collapse, closed selection, role order, manager-only unread, focus, full width, viewport, resize, ANSI colors, waiting input text, styled screen row mapping, wrapped hints, hint exclusion, menu priority, selection, same-pane sends, menu navigation, Tab hints, key deduplication, Backspace click, Backspace hold, busy repeat drop, enabled held button, busy release, blur stops repeat, keyboard send, append sends, empty Send menu guard, explicit menu Enter, empty Send presses Enter, drafts, pane ID reuse, joined-line reflow, history paging, scroll, reload, mobile)');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
